spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/grade-tracker-java
---
spring:
  config:
    activate:
      on-profile: dev
json-web-token:
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    expiration: 28800
---
spring:
  config:
    activate:
      on-profile: logger
logging:
  level:
    root: INFO
